# Neural Networks & Naïve Bayes

In [1]:
import pandas as pd

import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler


In [2]:
df_train = pd.read_csv('train_insurance_one_hot.csv')
df_test = pd.read_csv('test_insurance_one_hot.csv')
X_train_all_feat = df_train.drop(columns=['chargeGroup', 'id','charges'], axis=1)
X_test_all_feat = df_test.drop(columns=['chargeGroup', 'id','charges'], axis=1)

y_train = df_train['chargeGroup']
y_test = df_test['chargeGroup']

## a)

In [3]:
import numpy as np

classifier = MLPClassifier(hidden_layer_sizes=(5,5,5,5,5),
                           max_iter=2000, activation="logistic",random_state=42)
classifier.fit(X_train_all_feat, y_train)
Y_test_predictions = classifier.predict(X_test_all_feat)
confusion = confusion_matrix(y_test, Y_test_predictions)
accuracy = accuracy_score(y_test, Y_test_predictions)
print('Confusion Matrix of MLP:')
print(confusion)
print(f'Accuracy of MLP: {accuracy:.2f}')



Confusion Matrix of MLP:
[[ 31   0   2]
 [  0 131   0]
 [  7  12  85]]
Accuracy of MLP: 0.92


In [4]:
prob = classifier.predict_proba(X_test_all_feat)
class_variance = np.var(prob, axis=0) 
mask = (prob > 0.9) 
count_over_90 = np.sum(mask)

print(f'Number of instances with probabilities above 90%: {count_over_90}')
print(f'Number of total instances: {prob.shape[0]}')
print('Class_variance of MLP:', [f"{x:.2f}" for x in class_variance])
print('Probability estimates for the first five instances of the test set:')
for row in prob[:5, :]:
    print([f"{p:.2f}" for p in row])

Number of instances with probabilities above 90%: 195
Number of total instances: 268
Class_variance of MLP: ['0.08', '0.20', '0.15']
Probability estimates for the first five instances of the test set:
['0.00', '0.93', '0.07']
['0.00', '0.93', '0.07']
['0.00', '0.92', '0.08']
['0.00', '0.91', '0.09']
['0.02', '0.00', '0.98']


## b)

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_all_feat)
X_test_scaled = scaler.transform(X_test_all_feat)

classifier = MLPClassifier(hidden_layer_sizes=(5,5),
                           max_iter=2000, activation="logistic",random_state=42)
classifier.fit(X_train_scaled, y_train)
Y_test_predictions = classifier.predict(X_test_scaled)
confusion = confusion_matrix(y_test, Y_test_predictions)
accuracy = accuracy_score(y_test, Y_test_predictions)
print('Confusion Matrix of MLP:')
print(confusion)
print(f'Accuracy of MLP: {accuracy:.2f}')

Confusion Matrix of MLP:
[[ 32   0   1]
 [  0 131   0]
 [  4  12  88]]
Accuracy of MLP: 0.94


## c)

In [6]:
from sklearn.naive_bayes import GaussianNB


clf = GaussianNB()
# without scaling
clf.fit(X_train_all_feat,y_train)
Y_test_predictions = clf.predict(X_test_all_feat)
confusion = confusion_matrix(y_test, Y_test_predictions)
accuracy = accuracy_score(y_test, Y_test_predictions)
print('Confusion Matrix of GaussianNB without scaling:')
print(confusion)
print(f'Accuracy of GaussianNB without scaling: {accuracy:.2f}')

# with scaling
scaler = StandardScaler()
x_scaled_data_train= scaler.fit_transform(X_train_all_feat)
x_scaled_data_test= scaler.transform(X_test_all_feat)
clf.fit(x_scaled_data_train,y_train)
Y_test_predictions = clf.predict(x_scaled_data_test)
confusion = confusion_matrix(y_test, Y_test_predictions)
accuracy = accuracy_score(y_test, Y_test_predictions)
print('Confusion Matrix of GaussianNB with scaling:')
print(confusion)
print(f'Accuracy of GaussianNB with scaling: {accuracy:.2f}')

Confusion Matrix of GaussianNB without scaling:
[[ 33   0   0]
 [  0 131   0]
 [ 21  82   1]]
Accuracy of GaussianNB without scaling: 0.62
Confusion Matrix of GaussianNB with scaling:
[[ 33   0   0]
 [  0 131   0]
 [ 21  82   1]]
Accuracy of GaussianNB with scaling: 0.62
